from app.models import db, Caw


def seed_caws():
    caw1 = Caw(userId=1, caw='Is this working???')
    caw2 = Caw(userId=2, caw='Testing...')
    caw3 = Caw(userId=3, caw='I love crow')
    caw4 = Caw(userId=4, caw='I love app academy')
    caw5 = Caw(userId=6, caw='I love that you can comment on caws')
    caw6 = Caw(userId=5, caw='I love testing things')
    caw7 = Caw(userId=6, caw='Sup')
    caw8 = Caw(userId=7, caw='This my first day out here')
    caw9 = Caw(userId=4, caw='This was fun to make')
    caw10 = Caw(userId=8, caw='Who else likes propane???')
    caw11 = Caw(userId=3, caw='I cannot imagine life without sports')
    caw12 = Caw(userId=6, caw='This my first time on here I love it!!!')
    caw13 = Caw(userId=8, caw='Who uses charcoal when theres propane')
    caw14 = Caw(userId=7, caw='I hope Brian finishes the project')
    caw15 = Caw(userId=1, caw='I am a demo user')
    caw16 = Caw(userId=4, caw='My name is Brian Aguilar')
    caw17 = Caw(userId=5, caw='Is anyone there?')
    caw18 = Caw(userId=4, caw='Hope everything on the site works')
    caw19 = Caw(userId=3, caw='Bulls better win this year')
    caw20 = Caw(userId=8, caw='I love propane')

    db.session.add(caw1)
    db.session.add(caw2)
    db.session.add(caw3)
    db.session.add(caw4)
    db.session.add(caw5)
    db.session.add(caw6)
    db.session.add(caw7)
    db.session.add(caw8)
    db.session.add(caw9)
    db.session.add(caw10)
    db.session.add(caw11)
    db.session.add(caw12)
    db.session.add(caw13)
    db.session.add(caw14)
    db.session.add(caw15)
    db.session.add(caw16)
    db.session.add(caw17)
    db.session.add(caw18)
    db.session.add(caw19)
    db.session.add(caw20)
    db.session.commit()

def undo_caws():
    db.session.execute('TRUNCATE users RESTART IDENTITY CASCADE;')
    db.session.commit()
