from app.models import db, Comment


def seed_comments():
    comment1 = Comment(userId=2, cawId=1, data='Hello!!!')
    comment2 = Comment(userId=3, cawId=1, data='It sure is')
    comment3 = Comment(userId=1, cawId=2, data='What are you testing???')
    comment4 = Comment(userId=6, cawId=2, data="It's working")
    comment5 = Comment(userId=4, cawId=3, data='SAME!!!')
    comment6 = Comment(userId=8, cawId=3, data="It's the best!!!")
    comment7 = Comment(userId=5, cawId=4, data='I would have to agree')
    comment8 = Comment(userId=2, cawId=4, data="It's been so fun!!!")
    comment9 = Comment(userId=2, cawId=5, data='Im testing that right now')
    comment10 = Comment(userId=7, cawId=5, data='So I can add a comment???')
    comment11 = Comment(userId=3, cawId=6, data='Why?!?!')
    comment12 = Comment(userId=7, cawId=6, data='Its ok')
    comment13 = Comment(userId=1, cawId=7, data='Yo')
    comment14 = Comment(userId=5, cawId=7, data="What's up?")
    comment15 = Comment(userId=3, cawId=7, data='hi?')
    comment16 = Comment(userId=3, cawId=8, data='SAME!')
    comment17 = Comment(userId=5, cawId=8, data='What does that mean?')
    comment18 = Comment(userId=3, cawId=9, data='Ya I bet it was')
    comment19 = Comment(userId=1, cawId=9, data='It is pretty cool')
    comment20 = Comment(userId=2, cawId=10, data='Thats interesting')
    comment21 = Comment(userId=5, cawId=10, data='Very cool!!!')
    comment22 = Comment(userId=6, cawId=10, data='NICE!!!')
    comment23 = Comment(userId=2, cawId=11, data='Me neither')
    comment24 = Comment(userId=6, cawId=11, data='What sport you watch?')
    comment25 = Comment(userId=8, cawId=11, data='I can 0.0')
    comment26 = Comment(userId=2, cawId=12, data='Ya its great!!!')
    comment27 = Comment(userId=5, cawId=12, data='I saw you yesterday?')
    comment28 = Comment(userId=7, cawId=12, data='I told you to get on')
    comment29 = Comment(userId=1, cawId=13, data="Happens to me all the time")
    comment30 = Comment(userId=5, cawId=13, data='I feel that')
    comment31 = Comment(userId=7, cawId=13, data='My friends forget im a crow')
    comment32= Comment(userId=3, cawId=14, data='I do too :)')
    comment33 = Comment(userId=5, cawId=14, data='I think hes almost done')
    comment34 = Comment(userId=4, cawId=14, data='Almost there!!!')
    comment35 = Comment(userId=3, cawId=15, data='Thats cool')
    comment36 = Comment(userId=6, cawId=15, data='nice')
    comment37 = Comment(userId=2, cawId=15, data='ok???')
    comment38 = Comment(userId=3, cawId=16, data='You made this?')
    comment39 = Comment(userId=7, cawId=16, data='Hi Brian')
    comment40 = Comment(userId=8, cawId=16, data='sup')
    comment41 = Comment(userId=3, cawId=18, data='I am')
    comment42 = Comment(userId=8, cawId=18, data='Me?')
    comment43 = Comment(userId=1, cawId=18, data='What?')
    comment44 = Comment(userId=3, cawId=19, data='I cant say')
    comment45 = Comment(userId=1, cawId=19, data='seems fine')
    comment46 = Comment(userId=2, cawId=19, data='So far So good!!!')
    comment47 = Comment(userId=6, cawId=19, data='Si')
    comment48 = Comment(userId=7, cawId=19, data='Great job')
    comment49 = Comment(userId=8, cawId=19, data='its ok')
    comment50 = Comment(userId=6, cawId=17, data='Heyyy')
    comment51 = Comment(userId=4, cawId=17, data='hiii')
    comment52 = Comment(userId=2, cawId=17, data='???')
    comment53 = Comment(userId=2, cawId=21, data='Had one the other day')
    comment54 = Comment(userId=9, cawId=21, data='🙏🙏🙏')
    comment55 = Comment(userId=7, cawId=20, data='Bring back MJ')
    comment56 = Comment(userId=3, cawId=20, data='Facts')
    comment57 = Comment(userId=5, cawId=21, data='....')
    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
    db.session.add(comment31)
    db.session.add(comment32)
    db.session.add(comment33)
    db.session.add(comment34)
    db.session.add(comment35)
    db.session.add(comment36)
    db.session.add(comment37)
    db.session.add(comment38)
    db.session.add(comment39)
    db.session.add(comment40)
    db.session.add(comment41)
    db.session.add(comment42)
    db.session.add(comment43)
    db.session.add(comment44)
    db.session.add(comment45)
    db.session.add(comment46)
    db.session.add(comment47)
    db.session.add(comment48)
    db.session.add(comment49)
    db.session.add(comment50)
    db.session.add(comment51)
    db.session.add(comment52)
    db.session.add(comment53)
    db.session.add(comment54)
    db.session.add(comment55)
    db.session.add(comment56)
    db.session.add(comment57)
    db.session.commit()


def undo_comments():
    db.session.execute('TRUNCATE users RESTART IDENTITY CASCADE;')
    db.session.commit()
