"""empty message

Revision ID: a03a78bfa2ef
Revises: b4fecd5499dc
Create Date: 2022-11-01 10:14:19.814328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03a78bfa2ef'
down_revision = 'b4fecd5499dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caws', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caws', 'created_at')
    # ### end Alembic commands ###
