"""empty message

Revision ID: e3d9acd03435
Revises: 467fbe3e60ca
Create Date: 2022-09-13 16:33:59.909859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d9acd03435'
down_revision = '467fbe3e60ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caw_likes',
    sa.Column('cawId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cawId'], ['caws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cawId', 'userId')
    )
    op.drop_table('post_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('postId', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['caws.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postId', 'userId')
    )
    op.drop_table('caw_likes')
    # ### end Alembic commands ###
